// JSON object array that hold info for each team
var teamInfo = [{
			"team": "Chicago Cubs",
			"location": "Chicago, IL",
			"currentLeague": "National League",
			"stadiumName": "Wrigley Field",
			"stadiumAge": 103,
			"winningestManager": "Cap Anson",
			"yearsAsManager": "1879-1897",
			"careerWins": 1282,
			"winPercentage": 0.579,
			"bestPitcher": "Mordecai Brown",
			"pitcherERA": 1.8,
			"bestHitter": "Cap Anson",
			"battingAvg": 0.285,
			"playoffAppearences": 19,
			"pennantWins": 17,
			"worldSeriesWins": 3
		},
		{
			"team": "Cincinnati Reds",
			"location": "Cincinnati, OH",
			"currentLeague": "National League",
			"stadiumName": "Great American Ball Park",
			"stadiumAge": 14,
			"winningestManager": "Sparky Anderson",
			"yearsAsManager": "1970-1978",
			"careerWins": 2194,
			"winPercentage": 0.545,
			"bestPitcher": "Bob Ewing",
			"pitcherERA": 2.37,
			"bestHitter": "Pete Rose",
			"battingAvg": 0.307,
			"playoffAppearences": 15,
			"pennantWins": 10,
			"worldSeriesWins": 5
		},
		{
			"team": "Milwaukee Brewers",
			"location": "Milwaukee, WI",
			"currentLeague": "National League",
			"stadiumName": "Miller Park",
			"stadiumAge": 16,
			"winningestManager": "Phil Garner",
			"yearsAsManager": "1992-1999",
			"careerWins": 563,
			"winPercentage": 0.477,
			"bestPitcher": "Teddy Higuera",
			"pitcherERA": 3.61,
			"bestHitter": "Jeff Cirillo",
			"battingAvg": 0.296,
			"playoffAppearences": 4,
			"pennantWins": 1,
			"worldSeriesWins": 0
		},
		{
			"team": "Pittsburg Pirates",
			"location": "Pittsburg, PA",
			"currentLeague": "National League",
			"stadiumName": "PNC Park",
			"stadiumAge": 16,
			"winningestManager": "Fred Clarke",
			"yearsAsManager": "1900-1915",
			"careerWins": 1422,
			"winPercentage": 0.595,
			"bestPitcher": "Sam Leever",
			"pitcherERA": 2.47,
			"bestHitter": "Paul Molitor",
			"battingAvg": 0.303,
			"playoffAppearences": 17,
			"pennantWins": 9,
			"worldSeriesWins": 5
		},
		{
			"team": "St. Louis Cardinals",
			"location": "St. Louis, IL",
			"currentLeague": "National League",
			"stadiumName": "Busch Stadium",
			"stadiumAge": 11,
			"winningestManager": "Tony La Russa",
			"yearsAsManager": "1996-2011",
			"careerWins": 1408,
			"winPercentage": 0.544,
			"bestPitcher": "Bob Gibson",
			"pitcherERA": 2.91,
			"bestHitter": "Stan Musial",
			"battingAvg": 0.331,
			"playoffAppearences": 28,
			"pennantWins": 23,
			"worldSeriesWins": 11
		},
		{
			"team": "Chicago White Sox",
			"location": "Chicago, IL",
			"currentLeague": "American League",
			"stadiumName": "Guaranteed Rate Field",
			"stadiumAge": 26,
			"winningestManager": "Jimmy Dykes",
			"yearsAsManager": "1934-1946",
			"careerWins": 899,
			"winPercentage": 0.489,
			"bestPitcher": "Ed Walsh",
			"pitcherERA": 1.81,
			"bestHitter": "Eddie Collins Sr.",
			"battingAvg": 0.331,
			"playoffAppearences": 9,
			"pennantWins": 6,
			"worldSeriesWins": 3
		},
		{
			"team": "Cleveland Indians",
			"location": "Cleveland, OH",
			"currentLeague": "American League",
			"stadiumName": "Progressive Field",
			"stadiumAge": 23,
			"winningestManager": "Lou Boudreau",
			"yearsAsManager": "1942-1950",
			"careerWins": 728,
			"winPercentage": 0.529,
			"bestPitcher": "Bob Feller",
			"pitcherERA": 1.89,
			"bestHitter": "Nap Lajoie",
			"battingAvg": 0.34,
			"playoffAppearences": 13,
			"pennantWins": 6,
			"worldSeriesWins": 2
		},
		{
			"team": "Detroit Tigers",
			"location": "Detroit, MI",
			"currentLeague": "American League",
			"stadiumName": "Comerica Park",
			"stadiumAge": 17,
			"winningestManager": "Sparky Anderson",
			"yearsAsManager": "1979-1995",
			"careerWins": 1331,
			"winPercentage": 0.516,
			"bestPitcher": "George Mullin",
			"pitcherERA": 2.76,
			"bestHitter": "Ty Cobb",
			"battingAvg": 0.369,
			"playoffAppearences": 16,
			"pennantWins": 11,
			"worldSeriesWins": 4
		},
		{
			"team": "Kansas City Royals",
			"location": "Kansas City, MO",
			"currentLeague": "American League",
			"stadiumName": "Kauffman Stadium",
			"stadiumAge": 44,
			"winningestManager": "Ned Yost",
			"yearsAsManager": "2010-2017",
			"careerWins": 629,
			"winPercentage": 0.499,
			"bestPitcher": "Bret Saberhagen",
			"pitcherERA": 3.21,
			"bestHitter": "George Brett",
			"battingAvg": 0.305,
			"playoffAppearences": 9,
			"pennantWins": 4,
			"worldSeriesWins": 2
		},
		{
			"team": "Minnesota Twins",
			"location": "Minneapolis, MN",
			"currentLeague": "American League",
			"stadiumName": "Target Field",
			"stadiumAge": 7,
			"winningestManager": "Bucky Harris",
			"yearsAsManager": "1924-1954",
			"careerWins": 1336,
			"winPercentage": 0.485,
			"bestPitcher": "Walter Johnson",
			"pitcherERA": 2.17,
			"bestHitter": "Rod Carew",
			"battingAvg": 0.334,
			"playoffAppearences": 15,
			"pennantWins": 6,
			"worldSeriesWins": 3
		},
		{
			"team": "Boston Red Sox",
			"location": "Boston, MA",
			"currentLeague": "American League",
			"stadiumName": "Fenway Park",
			"stadiumAge": 105,
			"winningestManager": "Joe Cronin",
			"yearsAsManager": "1935-1947",
			"careerWins": 1071,
			"winPercentage": 0.539,
			"bestPitcher": "Cy Young",
			"pitcherERA": 2,
			"bestHitter": "Ted Williams",
			"battingAvg": 0.344,
			"playoffAppearences": 23,
			"pennantWins": 13,
			"worldSeriesWins": 8
		},
		{
			"team": "New York Yankees",
			"location": "Bronx, NY",
			"currentLeague": "American League",
			"stadiumName": "Yankee Stadium",
			"stadiumAge": 8,
			"winningestManager": "Joe McCarthy",
			"yearsAsManager": "1931-1946",
			"careerWins": 2125,
			"winPercentage": 0.609,
			"bestPitcher": "Mariano Rivera",
			"pitcherERA": 2.21,
			"bestHitter": "Babe Ruth",
			"battingAvg": 0.349,
			"playoffAppearences": 53,
			"pennantWins": 40,
			"worldSeriesWins": 27
		},
		{
			"team": "Tampa Bay Rays",
			"location": "St. Petersburg, FL",
			"currentLeague": "American League",
			"stadiumName": "Tropicana Field",
			"stadiumAge": 27,
			"winningestManager": "Joe Maddon",
			"yearsAsManager": "2006-2014",
			"careerWins": 754,
			"winPercentage": 0.517,
			"bestPitcher": "Jake McGee",
			"pitcherERA": 2.77,
			"bestHitter": "Carl Crawford",
			"battingAvg": 0.296,
			"playoffAppearences": 4,
			"pennantWins": 1,
			"worldSeriesWins": 0
		},
		{
			"team": "Toronto Blue Jays",
			"location": "Toronto, ON",
			"currentLeague": "American League",
			"stadiumName": "Rogers Centre",
			"stadiumAge": 28,
			"winningestManager": "Cito Gaston",
			"yearsAsManager": "1989-1997;2008-2010",
			"careerWins": 894,
			"winPercentage": 0.516,
			"bestPitcher": "Roy Halladay",
			"pitcherERA": 3.43,
			"bestHitter": "Tony Fernandez",
			"battingAvg": 0.297,
			"playoffAppearences": 7,
			"pennantWins": 2,
			"worldSeriesWins": 2
		},
		{
			"team": "Baltimore Orioles",
			"location": "Baltimore, MD",
			"currentLeague": "American League",
			"stadiumName": "Camden Yards",
			"stadiumAge": 25,
			"winningestManager": "Earl Weaver",
			"yearsAsManager": "1968-1982;1985-1986",
			"careerWins": 1480,
			"winPercentage": 0.583,
			"bestPitcher": "Harry Howell",
			"pitcherERA": 2.06,
			"bestHitter": "George Sister",
			"battingAvg": 0.362,
			"playoffAppearences": 14,
			"pennantWins": 7,
			"worldSeriesWins": 3
		},
		{
			"team": "Washington Nationals",
			"location": "Washington D.C",
			"currentLeague": "National League",
			"stadiumName": "Nationals Park",
			"stadiumAge": 9,
			"winningestManager": "Felipe Alou",
			"yearsAsManager": "1992-2001",
			"careerWins": 691,
			"winPercentage": 0.491,
			"bestPitcher": "Steve Rogers",
			"pitcherERA": 3.17,
			"bestHitter": "Tim Raines",
			"battingAvg": 0.323,
			"playoffAppearences": 14,
			"pennantWins": 7,
			"worldSeriesWins": 3
		},
		{
			"team": "Miami Marlins",
			"location": "Miami, FL",
			"currentLeague": "National League",
			"stadiumName": "Marlins Park",
			"stadiumAge": 5,
			"winningestManager": "Jack McKeon",
			"yearsAsManager": "2003-2005;2011",
			"careerWins": 281,
			"winPercentage": 0.522,
			"bestPitcher": "Josh Johnson",
			"pitcherERA": 3.15,
			"bestHitter": "Miguel Cabrera",
			"battingAvg": 0.313,
			"playoffAppearences": 2,
			"pennantWins": 2,
			"worldSeriesWins": 2
		},
		{
			"team": "Atlanta Braves",
			"location": "Atlanta, GA",
			"currentLeague": "National League",
			"stadiumName": "Sun Trust Park",
			"stadiumAge": 1,
			"winningestManager": "Bobby Cox",
			"yearsAsManager": "1978-1981;1990-2010",
			"careerWins": 2149,
			"winPercentage": 0.557,
			"bestPitcher": "Greg Maddux",
			"pitcherERA": 2.63,
			"bestHitter": "Hank Aaron",
			"battingAvg": 0.31,
			"playoffAppearences": 23,
			"pennantWins": 17,
			"worldSeriesWins": 3
		},
		{
			"team": "New York Mets",
			"location": "Queens, NY",
			"currentLeague": "National League",
			"stadiumName": "Citi Field",
			"stadiumAge": 8,
			"winningestManager": "Davey Johnson",
			"yearsAsManager": "1984-1990",
			"careerWins": 595,
			"winPercentage": 0.588,
			"bestPitcher": "Tom Seaver",
			"pitcherERA": 2.57,
			"bestHitter": "David Wright",
			"battingAvg": 0.296,
			"playoffAppearences": 9,
			"pennantWins": 5,
			"worldSeriesWins": 2
		},
		{
			"team": "Philadelphia Phillies",
			"location": "Philadelphia, PA",
			"currentLeague": "National League",
			"stadiumName": "Citizens Bank Park",
			"stadiumAge": 13,
			"winningestManager": "Charlie Manuel",
			"yearsAsManager": "2005-2013",
			"careerWins": 780,
			"winPercentage": 0.551,
			"bestPitcher": "Grover Alexander",
			"pitcherERA": 2.18,
			"bestHitter": "Ed Delahanty",
			"battingAvg": 0.348,
			"playoffAppearences": 14,
			"pennantWins": 7,
			"worldSeriesWins": 2
		},
		{
			"team": "Houston Astros",
			"location": "Houston, TX",
			"currentLeague": "American League",
			"stadiumName": "Minute Maid Park",
			"stadiumAge": 17,
			"winningestManager": "Bill Virdon",
			"yearsAsManager": "1975-1982",
			"careerWins": 544,
			"winPercentage": 0.510,
			"bestPitcher": "Nolan Ryan",
			"pitcherERA": 3.13,
			"bestHitter": "Jeff Bagwell",
			"battingAvg": 0.297,
			"playoffAppearences": 11,
			"pennantWins": 2,
			"worldSeriesWins": 0
		},
		{
			"team": "Los Angeles Angels",
			"location": "Anaheim, CA",
			"currentLeague": "American League",
			"stadiumName": "Angel Stadium",
			"stadiumAge": 51,
			"winningestManager": "Mike Scioscia",
			"yearsAsManager": "2000-2017",
			"careerWins": 1570,
			"winPercentage": 0.538,
			"bestPitcher": "Francisco Rodriguez",
			"pitcherERA": 2.35,
			"bestHitter": "Garret Anderson",
			"battingAvg": 0.296,
			"playoffAppearences": 10,
			"pennantWins": 1,
			"worldSeriesWins": 1
		},
		{
			"team": "Seattle Mariners",
			"location": "Seattle, WA",
			"currentLeague": "American League",
			"stadiumName": "Safeco Field",
			"stadiumAge": 18,
			"winningestManager": "Lou Piniella",
			"yearsAsManager": "1993-2002",
			"careerWins": 840,
			"winPercentage": 0.542,
			"bestPitcher": "Felix Hernandez",
			"pitcherERA": 3.2,
			"bestHitter": "Ichiro Suzuki",
			"battingAvg": 0.322,
			"playoffAppearences": 4,
			"pennantWins": 0,
			"worldSeriesWins": 0
		},
		{
			"team": "Texas Rangers",
			"location": "Arlington, TX",
			"currentLeague": "American League",
			"stadiumName": "Globe Life Park",
			"stadiumAge": 23,
			"winningestManager": "Ron Washington",
			"yearsAsManager": "2007-2014",
			"careerWins": 664,
			"winPercentage": 0.521,
			"bestPitcher": "Nolan Ryan",
			"pitcherERA": 3.43,
			"bestHitter": "Michael Young",
			"battingAvg": 0.301,
			"playoffAppearences": 8,
			"pennantWins": 2,
			"worldSeriesWins": 0
		},
		{
			"team": "Oakland Athletics",
			"location": "Oakland, CA",
			"currentLeague": "American League",
			"stadiumName": "Oakland Alameda Coliseum",
			"stadiumAge": 51,
			"winningestManager": "Connie Mack",
			"yearsAsManager": "1901-1950",
			"careerWins": 3582,
			"winPercentage": 0.484,
			"bestPitcher": "Eddie Plank",
			"pitcherERA": 2.39,
			"bestHitter": "Al Simmons",
			"battingAvg": 0.356,
			"playoffAppearences": 26,
			"pennantWins": 15,
			"worldSeriesWins": 9
		},
		{
			"team": "Los Angeles Dodgers",
			"location": "Los Angeles, CA",
			"currentLeague": "National League",
			"stadiumName": "Dodger Stadium",
			"stadiumAge": 17,
			"winningestManager": "Walter Alston",
			"yearsAsManager": "1985-1976",
			"careerWins": 2040,
			"winPercentage": 0.558,
			"bestPitcher": "Sandy Koufax",
			"pitcherERA": 2.76,
			"bestHitter": "Steve Garvey",
			"battingAvg": 0.301,
			"playoffAppearences": 31,
			"pennantWins": 23,
			"worldSeriesWins": 6
		},
		{
			"team": "Arizona Diamondbacks",
			"location": "Phoenix, AZ",
			"currentLeague": "National League",
			"stadiumName": "Chase Field",
			"stadiumAge": 19,
			"winningestManager": "Kirk Gibson",
			"yearsAsManager": "2010-2014",
			"careerWins": 353,
			"winPercentage": 0.485,
			"bestPitcher": "Randy Johnson",
			"pitcherERA": 2.83,
			"bestHitter": "Luis Gonzalez",
			"battingAvg": 0.298,
			"playoffAppearences": 6,
			"pennantWins": 1,
			"worldSeriesWins": 1
		},
		{
			"team": "Colorado Rockies",
			"location": "Denver, Co",
			"currentLeague": "National League",
			"stadiumName": "Coors Field",
			"stadiumAge": 22,
			"winningestManager": "Clint Hurdle",
			"yearsAsManager": "2002-2009",
			"careerWins": 534,
			"winPercentage": 0.461,
			"bestPitcher": "Aaron Cook",
			"pitcherERA": 4.53,
			"bestHitter": "Todd Helton",
			"battingAvg": 0.316,
			"playoffAppearences": 4,
			"pennantWins": 1,
			"worldSeriesWins": 0
		},
		{
			"team": "San Diego Padres",
			"location": "San Diego, CA",
			"currentLeague": "National League",
			"stadiumName": "Petco Park",
			"stadiumAge": 13,
			"winningestManager": "Bruce Bochy",
			"yearsAsManager": "1995-2005",
			"careerWins": 951,
			"winPercentage": 0.494,
			"bestPitcher": "Bruce Hurst",
			"pitcherERA": 3.27,
			"bestHitter": "Tony Gwynn",
			"battingAvg": 0.338,
			"playoffAppearences": 5,
			"pennantWins": 2,
			"worldSeriesWins": 0
		},
		{
			"team": "San Francisco Giants",
			"location": "San Francisco, CA",
			"currentLeague": "National League",
			"stadiumName": "National Park",
			"stadiumAge": 17,
			"winningestManager": "John McGraw",
			"yearsAsManager": "1902-1932",
			"careerWins": 2583,
			"winPercentage": 0.591,
			"bestPitcher": "Christy Mathewson",
			"pitcherERA": 2.12,
			"bestHitter": "Bill Terry",
			"battingAvg": 0.341,
			"playoffAppearences": 26,
			"pennantWins": 23,
			"worldSeriesWins": 8
		}];

// searches for a given team in the json object array
function getTeam(team){
  var thisTeam;
  for(var i = 0;i<teamInfo.length;i++){
   if (team === teamInfo[i].team){
     thisTeam = teamInfo[i];
   }
  }
  output(thisTeam);
}

// appends the team info onto the page 
function output(team){
	// clears out any existing html in the info div 
  $("#teamInfo").empty();
  var infoDiv ="<h2><b>" + team.team + "</b></h2>"+
      "<img src='Real Stadium Pics/" + team.stadiumName + ".jpg' id='stadiumPic'>" +
	  "<h4>" + team.stadiumName + "</h4>" +
	  "<table><tr><td> Location: " + team.location + "</td></tr>" +
	  "<tbody><tr><td> Open " + team.stadiumAge + " years</td></tr></tbody></table>" +
	  "<table><tbody><tr><td> Current League: " + team.currentLeague + "</td></tr>" +
      "<tr><td> Playoff Appearances: " + team.playoffAppearences + "</td></tr>" +
      "<tr><td> Pennant Wins: " + team.pennantWins + "</td></tr>" +
      "<tr><td> World Series Wins: " + team.worldSeriesWins + "</td></tr></tbody></table>" +
      "<table><thead><th> Winningest Manager: " + team.winningestManager + "</th></thead>" +
      "<tbody><tr><td> Years as Manager: " + team.yearsAsManager + "</td></tr>" +
      "<tr><td> Career Wins: " + team.careerWins + "</td></tr>" +
      "<tr><td> Win Percentage: " + team.winPercentage + "</td></tr></tbody></table>" +
      "<table><thead><th> Best Pitcher: " + team.bestPitcher + "</th></thead>" +
      "<tbody><tr><td> ERA: " + team.pitcherERA + "</td></tr></tbody></table>" +
      "<table><thead><th> Best Hitter: " + team.bestHitter + "</th></thead>" +
      "<tbody><tr><td> Batting Average: " + team.battingAvg + "</td></tr></tbody></table>";
  $("#teamInfo").append(infoDiv).hide().slideDown(2000);
}